### ISSUE TITLE
"cmd+shift+I" A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by MusculusMus** [GeoffreyChen777/paperlib#100]
cmd+shift+I to insert citation, error shows up.

A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Error processing argument at index 1, conversion failure from 
at Function.<anonymous> (/Applications/Paperlib.app/Contents/Resources/app.asar/dist/main/index.cjs:35:2326)

Model Name:	MacBook Pro Chip:	Apple M1 Pro

<img width="278" alt="Screen Shot 2022-06-27 at 11 30 16" src="https://user-images.githubusercontent.com/37739300/175977607-dd57549f-fb85-478d-9ea7-c1c88dc18445.png">

**Comment by GeoffreyChen777** [comment]
Sorry I cannot reproduce this issue. Could you please try to restart paperlib, or provide more details?

**Comment by GeoffreyChen777** [comment]
OK, I will try my best to figure it out. Thanks for your information.

**Comment by GeoffreyChen777** [comment]
It seems that the issue is caused by the screen resolution.

Could you please provide your screen settings? macbook builtin screen or external screen?

```
      const { x, y } = screen.getCursorScreenPoint();
      const currentDisplay = screen.getDisplayNearestPoint({ x, y });
      const bounds = currentDisplay.bounds;
      const centerx = bounds.x + (bounds.width - 600) / 2;
      const centery = bounds.y + (bounds.height - 48) / 2;
      winPlugin?.setPosition(centerx, centery);
```

this code is trying to set the position of the plugin window to the center point of your screen. But on your computer, it seems that the `centery` is invalid. I wanna know the exact number of this `centery`. Do you have any IM such as wechat, or whatsapp? I may need to send you a testing package to help me fix this issue if it is ok for you.

**Comment by MusculusMus** [comment]
My WeChat ID: psychrophile

shuai wang

________________________________
发件人: GeoffreyChen777 ***@***.***>
发送时间: Monday, June 27, 2022 5:32:08 PM
收件人: GeoffreyChen777/paperlib ***@***.***>
抄送: Shuai Wang ***@***.***>; Author ***@***.***>
主题: Re: [GeoffreyChen777/paperlib] "cmd+shift+I" A JavaScript error occurred in the main process (Issue #100)


It seems that the issue is caused by the screen resolution.

Could you please provide your screen settings? macbook builtin screen or external screen?

      const { x, y } = screen.getCursorScreenPoint();
      const currentDisplay = screen.getDisplayNearestPoint({ x, y });
      const bounds = currentDisplay.bounds;
      const centerx = bounds.x + (bounds.width - 600) / 2;
      const centery = bounds.y + (bounds.height - 48) / 2;
      winPlugin?.setPosition(centerx, centery);


this code is trying to set the position of the plugin window to the center point of your screen. But on your computer, it seems that the centery is invalid. I wanna know the exact number of this centery. Do you have any IM such as wechat, or whatsapp? I may need to send you a testing package to help me fix this issue if it is ok for you.

―
