### ISSUE TITLE
[Feature Request] Adjustable left panel width.

### ISSUE THREAD

**Issue by Mrz-zz** [GeoffreyChen777/paperlib#103]
1. the left panel's width cannot be adjusted, it is set to be a fixed value, is this a bug?
2. I can't create folders, when clicking the folder button, nothing happened.
3. the app still needs to be run by Rosetta2, will it be supported apple silicon natively?

---

1. 侧边栏不能够调整，是固定大小，宽度无法自行调整
2. 无法添加Folders，点击无反应
3. 可否支持apple silicon芯片，目前仍需转译运行

**Comment by GeoffreyChen777** [comment]
1. Not a bug.
2. Currently you cannot creat an empty folder. If you wanna creat a folder, you need to open the edit view of a paper and creat a folder for it.
3. I don’t have a silicon Mac, so it is hard for me to debug Paperlib on it.

**Comment by Mrz-zz** [comment]
1. As for the first question, will it be supported to change the panel width in the future version? Especially for the left panel, the default width on my MacBook seems a little wide.
2. As for the second problem, just from my own perspective :), it will be more intuitive to create a new folder when I move my cursor to the Folder button. Like the Zotero Does.

**Comment by GeoffreyChen777** [comment]
1. Yes
2. The ’tag’ is the inherent attributes of a paper such as classification, detection. The ‘folder’ indicates the attributes given by the user. For example, a paper may be placed in a folder group called ‘good writing’. So in the design of Paperlib, no empty folder should be created.

**Comment by Mrz-zz** [comment]
OK, hope that Paperlib can perform better in the future version(running fluency and memory consuming). Thanks for creating such a beautiful and elegant application! 

Maybe oneday I can just use this app to finish my paper organization.

**Comment by GeoffreyChen777** [comment]
Thanks, Electron version does require more memory than native version. But it is friendly for me to maintain two platforms(Mac and win). I found currently Paperlib consumes less memory than zotero.

**Comment by Mrz-zz** [comment]
Besides, I just find that the app cannot be in full screen.

**Comment by GeoffreyChen777** [comment]
Yes, the window control button is not the macOS native window control button. It is used to toggle the window maximization:

https://github.com/GeoffreyChen777/paperlib/blob/d7f8d2e6af7b915a8cab59068530fa1ea112f1ee/packages/main/index.ts#L199-L205

**Comment by GeoffreyChen777** [comment]
solved.

**Comment by GeoffreyChen777** [comment]
@Mrz-zz Hi, now you can try the Apple silicon version:

https://paperlib.app/en/download/

Please reopen this issue if you meet any bug.

**Comment by Mrz-zz** [comment]
<img width="480" alt="image" src="https://user-images.githubusercontent.com/36831062/177439455-c36214e0-7672-44c9-8e76-cf068f16b5b5.png">

Something Wrong!

**Comment by Mrz-zz** [comment]
Right now, it still cannot run natively on apple silicon.

**Comment by GeoffreyChen777** [comment]
Is that ok? @Mrz-zz You need to download and reinstall Paperlib. Please click the link for Apple silicon.

**Comment by Mrz-zz** [comment]
@GeoffreyChen777 Sorry for that. I found I do not download the beta version. Now it is OK!

**Comment by GeoffreyChen777** [comment]
> @GeoffreyChen777 Sorry for that. I found I do not download the beta version. Now it is OK!

👌
