### ISSUE TITLE
Apple Silicon

### ISSUE THREAD

**Issue by GeoffreyChen777** [GeoffreyChen777/paperlib#105]
Because I don't have a silicon mac, it is hard for me to debug Paperlib on it.

If anyone wanna help me do that, please contact me.

Download link:

https://paperlib.app/en/download/

**Comment by Randy-Zhang233** [comment]
🙋

**Comment by jisuoqing** [comment]
Happy to help test on Apple Silicon, but not sure about detailed debugging.
