### ISSUE TITLE
DOI / Google Scholar scraper error

### ISSUE THREAD

**Issue by jisuoqing** [GeoffreyChen777/paperlib#106]
Error messages are as follows:
`DOIScraper error: HTTPError: Response code 404 (Not Found)`
`GoogleScholarScraper error: TypeError: Cannot read properties of undefined (reading 'length")`

Testing file: https://www.dropbox.com/s/5lzknfsudts87f3/Ostriker_0000_Theoretical_Challenges_in_Galaxy_Formation_62c4fb4233a81b3e2dfcf97f_main.pdf

**Comment by tang1heng** [comment]
<img width="276" alt="image" src="https://user-images.githubusercontent.com/48460831/177460731-42c1f669-a89d-4b6d-b1e2-025ceb332fbf.png">

**Comment by tang1heng** [comment]
This problem occurs on both intel and apple chip macbook.

**Comment by GeoffreyChen777** [comment]
@jisuoqing hi, only this paper right?

**Comment by tang1heng** [comment]
@GeoffreyChen777 https://scholar.google.com/scholar?hl=zh-CN&as_sdt=0%2C5&q=V-Net%3A+Fully+Convolutional+Neural+Networks+for+Volumetric+Medical+Image+Segmentation&btnG=

**Comment by jisuoqing** [comment]
https://scholar.google.com/scholar?cluster=5850684734190267831&hl=en&as_sdt=0,5

In fact, it might be even easier to use NASA database for scraper: https://ui.adsabs.harvard.edu/abs/2017ARA%26A..55...59N/abstract

**Comment by GeoffreyChen777** [comment]
@tang1heng Hi, I cannot reproduce your issue.

<img width="1210" alt="image" src="https://user-images.githubusercontent.com/14183213/177503237-cc55a26c-e5e8-43cb-b7eb-21434a898789.png">

Are you in China mainland? Because Google scholar cannot be accessed in China mainland.

**Comment by jisuoqing** [comment]
Btw, I understand you might have lots of research work to do, so no hurries on these issues.

**Comment by GeoffreyChen777** [comment]
@jisuoqing Hi, currently, Paperlib only focuses on computer science, the CS community doesn't usually use NASA database...

But I found that your paper has a DOI, but cannot be extracted as expected. The reason is that there is a ‘newline control character’ in the DOI string:

<img width="351" alt="image" src="https://user-images.githubusercontent.com/14183213/177504489-e1178226-2dd2-4655-b0d8-cbf380d49966.png">

Let me try to solve this DOI issue first.

**Comment by jisuoqing** [comment]
> @jisuoqing Hi, currently, Paperlib only focuses on computer science, the CS community doesn't usually use NASA database...
Make sense. So #44 is very intriguing.

**Comment by GeoffreyChen777** [comment]
fixed both.
