### ISSUE TITLE
[feature request] moving files to Trash instead of deleting permanently

### ISSUE THREAD

**Issue by jisuoqing** [GeoffreyChen777/paperlib#107]
This might be considered that when a paper is deleted from PaperLib, it will be moved to Trash instead of being `rm` permanently. Otherwise, you cannot "undo" it.

**Comment by GeoffreyChen777** [comment]
After investigation, it is hard to access the trash bin in nodejs.

Node.js do not provide any API to do that. The trash bin path is hidden and unaccessible.

**Comment by jisuoqing** [comment]
Indeed. Some third-party could do so, e.g., https://github.com/sindresorhus/trash, but don't feel obligated to implement this feature.

**Comment by GeoffreyChen777** [comment]
I tried this, but unfortunately, find some compatibility issues.

I will do this once I found a feasible way.

**Comment by GeoffreyChen777** [comment]
Hi I found a way to solve this issue and it is implemented in v2.0.0.
