### ISSUE TITLE
[Feature Request] Dialog window hotkey

### ISSUE THREAD

**Issue by jisuoqing** [GeoffreyChen777/paperlib#108]
Any dialog window cannot respond to keyboard input.

For instance, a confirmation message (`ok` or `cancel`) appears when you delete a file. But when you hit the `enter/return` key from the keyboard, the keyboard entry does not act on the confirmation message to delete the file, instead, the file is opened and the the dialog window remains.

**Comment by GeoffreyChen777** [comment]
The reason is that the dialog in Paperlib is not a real 'dialog'. It is just a view consists of some text and buttons. Currently, I bind no hotkey for these buttons.

Will consider this. Thanks!

**Comment by GeoffreyChen777** [comment]
supported.
