### ISSUE TITLE
[BUG] The what's new window cannot be closed after updating on small screen.

### ISSUE THREAD

**Issue by tang1heng** [GeoffreyChen777/paperlib#109]
<img width="1460" alt="image" src="https://user-images.githubusercontent.com/48460831/178135476-f1b53912-4729-460d-9634-05acabc5d2df.png">

**Comment by GeoffreyChen777** [comment]
Could you please try to resize the window, increase the height.

**Comment by tang1heng** [comment]
@GeoffreyChen777  Still cannot click the close button. QAQ

**Comment by GeoffreyChen777** [comment]
Click the 'Toggle Developer Tools' in the View Menu.
<img width="281" alt="Screenshot 2022-07-10 at 08 42 14" src="https://user-images.githubusercontent.com/14183213/178135880-39e3fbc0-51e2-448d-8ef0-7cfda06d3c47.png">

Find and delete this element, then you can click close button.
<img width="850" alt="Screenshot 2022-07-10 at 08 43 45" src="https://user-images.githubusercontent.com/14183213/178135939-d311fca1-328d-4b5f-bb12-f0af6a6dbd03.png">

**Comment by tang1heng** [comment]
@GeoffreyChen777 It's working, thank you.

**Comment by GeoffreyChen777** [comment]
I guess you are using a laptop screen which is relatively small. I found that the bottom mask may cover the button when the screen size is small. Thanks for reporting this.
