### ISSUE TITLE
[Feature Request] Could I choose to show notes of papers in the main page?

### ISSUE THREAD

**Issue by PengFoo** [GeoffreyChen777/paperlib#112]
Hi,

Thanks for your great work! I have been using this app the manage all my papers now and it is working really well!

Sometimes when I explorer my paper list or find a paper, I cannot remember details of every paper till I clicked the detail and check the notes, so I have to click every paper in the list to check the detail notes. Could we add a feature that show notes of papers in the main page so that I can check my notes easier?

Thanks a lot for your reading and your brilliant work again!

**Comment by GeoffreyChen777** [comment]
will consider. Currently you can try to search notes by inputting some keywords into the search bar.

**Comment by GeoffreyChen777** [comment]
Hi, @PengFoo 

I tried to design and implement this feature. Here is a preview:

<img width="831" alt="image" src="https://user-images.githubusercontent.com/14183213/179374419-f0e89398-a6dc-43a8-9994-1320e243660d.png">

The details part of a paper item is now configurable. Here the note is: _ResNet, proposed a residual architecture to train very deep models._

Does that meet your needs?

**Comment by GeoffreyChen777** [comment]
implemented in v1.8.2

**Comment by PengFoo** [comment]
That looks pretty good to me! 
thx!
