### ISSUE TITLE
[bug report] Can't added a paper item when scraped failed!

### ISSUE THREAD

**Issue by Mrz-zz** [GeoffreyChen777/paperlib#115]
Hello! :)

When I drag and drop a PDF file onto the main view of Paperlib, the paper matching nothing in provided databases will not create an empty paper item. So I can't add this paper to Paperlib anymore :(

the paper's I tried to add is: https://www.nature.com/articles/s41467-018-07931-2

I reproduce this bug both on my Intel MacBook and Apple silicon Mac mini.

the software's version: 1.8.2

**Comment by GeoffreyChen777** [comment]
Sorry I cannot reproduce this bug. Have you turned the pdfbuiltin scraper on?
![6EFB9539-7070-4FF5-9C5B-2D62C649C339](https://user-images.githubusercontent.com/14183213/180398159-ad2bf468-5b91-4cdd-bda5-08227479310a.jpeg)

**Comment by Mrz-zz** [comment]
<img width="261" alt="Screen Shot 2022-07-22 at 16 32 09" src="https://user-images.githubusercontent.com/36831062/180398652-e0451495-a16d-4810-9357-cfeeb2f19b95.png">

I got this warning.

**Comment by GeoffreyChen777** [comment]
Interesting 🤔 as I cannot reproduce this bug, plz give me some time to figure it out. For now, you can try to add another PDF to create a paper item, manually edit its info, and replace the pdf file by right clicking the the pdf preview image. I will fix this in the next version.

**Comment by GeoffreyChen777** [comment]
I've reproduced this bug.

The reason is that it seems that you can not connect to the doi.org, thereby the low-priority google scholar scraped this paper's metadata. The response of google scholar contains a character `"` which caused this bug.

Thanks for reporting this. I'm fixing it.

**Comment by GeoffreyChen777** [comment]
fixed
