### ISSUE TITLE
Cannot reopen window on macOS

### ISSUE THREAD

**Issue by Yienschwen** [GeoffreyChen777/paperlib#118]
## To replicate
1. Use `Command-W` to close window, note that app icon remains in dock
2. Click app icon in dock, the error window pops as follows.

![image](https://user-images.githubusercontent.com/16430672/180698735-d4299f7c-effb-46e0-98d8-fe52fbbf8870.png)

**Comment by GeoffreyChen777** [comment]
If you use the close button to close app, will this happen?

**Comment by Yienschwen** [comment]
> If you use the close button to close app, will this happen?

No, it only happens when I use the keyboard shortcut.

**Comment by GeoffreyChen777** [comment]
ok, will fix it in the next version

**Comment by jisuoqing** [comment]
The same error occur if you restarted your Mac when leaving paperLib launched (it will fail to relaunch after the Mac restarted, showing the same error).

**Comment by GeoffreyChen777** [comment]
@Yienschwen The bug you mentioned is fixed in v1.9.1. Now, when you press cmd+w, Paperlib will not really quit, it's just being hidden, just like many other softwares perform. If you want to close Paperlib, please press cmd+q or right click the dock icon.

**Comment by GeoffreyChen777** [comment]
@jisuoqing I cannot reproduce your mentioned bug, but I still tired to fix it in v1.9.1. If it still occurs on your machine, please let me know and provide more info. Let this issue be open for now.

**Comment by jisuoqing** [comment]
The latest update causes a severe issue: `ctrl + w` command indeed closes PaperLib window, however, all other Applications on macOS fails to respond to `ctrl + w` command (does not close their windows), until PaperLib shuts down completely.

**Comment by Yienschwen** [comment]
> The latest update causes a severe issue: `cmd + w` command indeed closes PaperLib window, however, all other Applications on macOS fail to respond to `cmd + w` command (do not close their windows), unless PaperLib shuts down completely.

Yes, confirmed on macOS 12.4 arm64 as well.

**Comment by GeoffreyChen777** [comment]
@jisuoqing @Yienschwen Fixed, wait 5mins for the new build v1.9.2.
