### ISSUE TITLE
Support Safari extension

### ISSUE THREAD

**Issue by xiajunwen1007** [GeoffreyChen777/paperlib#121]
It would be excellent if it supported safari extension like zotero and papers.

**Comment by GeoffreyChen777** [comment]
Hi, Safari extension requires Apple Developer Account, which is expensive to me. $99/year.

Currently I just received one donation. As a student I don't have money to pay for a developer account.

Sorry for that.

**Comment by xiajunwen1007** [comment]
Zotero bundles the safari extension in their app and do not release it in apple store. Maybe, It is possible to follow the way of zotero?

**Comment by GeoffreyChen777** [comment]
I tried to build a safari extension, here is the download link, feel free to try it.

https://paperlib.app/en/download/

It's still a beta version cuz I'm not very familiar with the safari extension coding.

**Comment by hairfull** [comment]
What about edge extension?

**Comment by GeoffreyChen777** [comment]
@hairfull EDGE  can directly use the chrome extension. Just go to the download page of the Chrome extension and install it.

**Comment by hairfull** [comment]
thanks




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "GeoffreyChen777/paperlib"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月23日(星期五) 晚上7:01
***@***.***&gt;;
抄送:&nbsp;" ***@***.******@***.***&gt;;
主题:&nbsp;Re: [GeoffreyChen777/paperlib] Support Safari extension (Issue #121)





 
@hairfull EDGE  can directly use the chrome extension. Just go to the download page of the Chrome extension and install it.
