### ISSUE TITLE
Support getting pdf from scihub

### ISSUE THREAD

**Issue by xiajunwen1007** [GeoffreyChen777/paperlib#122]

**Comment by GeoffreyChen777** [comment]
I have no idea what's the role of Sci-hub in Paperlib.

You need to drag a PDF to Paperlib to import it, which means you already downloaded this PDF file.

Could you please describe the scenario in which you want to use scihub.

**Comment by xiajunwen1007** [comment]
Sometimes when importing paper from the chrome extension, without access to the pdf,  extension only saves basic information to paperlib. It would be great if paperlib can download the pdf from scihub. However, it may violate copyright of publisher. I have no idea of voiding such violation but a customized pdf downloader engine. Thus people can customize it to scihub.

**Comment by GeoffreyChen777** [comment]
Ok, I'm afraid the only thing that I can do is a pdf downloader engine without any specific database url. Because there is a legal risk in my country if I provide any relevant feature of SciHub.

**Comment by GeoffreyChen777** [comment]
BTW, I have no idea about the estimated release time about this feature, because I'm working on my own research work recently. If you want to implement this feature, I'm happy to any PR.

**Comment by GeoffreyChen777** [comment]
Hi, @xiajunwen1007 ,

This has been implemented in v1.9.6, feel free to try it!
