### ISSUE TITLE
Papers from the ACL conference will be mistakenly identified from AMTA conference

### ISSUE THREAD

**Issue by layer-3** [GeoffreyChen777/paperlib#127]
Examples:
- https://aclanthology.org/2022.acl-long.238/
- https://aclanthology.org/2020.acl-main.9/

**Comment by GeoffreyChen777** [comment]
Hi thanks for report this. Could you please list some main conferences and journals of NLP. So I can add some metadata scrapers for them.

**Comment by layer-3** [comment]
Hello, thanks for reply. Since I only know some high-impact conference of NLP, here is the link of similar question in Quora. 
- https://qr.ae/pG6D2Q

Hope this can do help.

**Comment by GeoffreyChen777** [comment]
Hi, this bug is fixed now in v1.9.7. It's building and publishing now, please reopen/check update paperlib after 10 mins.

I'll develop some scrapers for NLP in the next few versions.
