### ISSUE TITLE
可以指定打开方式吗

### ISSUE THREAD

**Issue by hairfull** [GeoffreyChen777/paperlib#128]
请问可以指定打开方式嘛，比如自己设定用哪个阅读器打开pdf😉

**Comment by GeoffreyChen777** [comment]
你好现在的打开方式就是你系统的默认的方式， 可以修改系统的默认PDF打开软件。请问您是不想修改默认方式的情况下来使用别的软件打开嘛？

**Comment by hairfull** [comment]
是想用文献划词翻译软件打开哈哈哈（觉得如果支持划词翻译可能是个需求？当然也可能只有我不直接读原文）




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "GeoffreyChen777/paperlib"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月23日(星期二) 晚上6:00
***@***.***&gt;;
抄送:&nbsp;" ***@***.******@***.***&gt;;
主题:&nbsp;Re: [GeoffreyChen777/paperlib] 可以指定打开方式吗 (Issue #128)





 
你好现在的打开方式就是你系统的默认的方式， 可以修改系统的默认PDF打开软件。请问您是不想修改默认方式的情况下来使用别的软件打开嘛？

**Comment by GeoffreyChen777** [comment]
哦哦，目前 Paperlib 应该是不会支持浏览 PDF 的功能的。目前的定位是管理软件，PDF 阅读器有大量的优秀的阅读器，所以自己做一个这样的功能，没法说能不能做的比别人好，而且也会让 Paperlib 变得臃肿。

目前最贴近你的使用方式的操作是：

右键一篇论文，点击 Show in Finder/Explore ，然后就会打开文件管理器了。在里面，你右键那个文件，再通过系统的右键菜单选择用任何你喜欢的软件打开就可以了。

会考虑直接把 ‘使用 xxx 打开’ 这种功能加到 Paperlib 的右键菜单里，但是临时应该不会考虑内置 PDF 阅读器。

**Comment by hairfull** [comment]
好的谢谢，祝你们越做越好！

**Comment by layer-3** [comment]
> 



> 哦哦，目前 Paperlib 应该是不会支持浏览 PDF 的功能的。目前的定位是管理软件，PDF 阅读器有大量的优秀的阅读器，所以自己做一个这样的功能，没法说能不能做的比别人好，而且也会让 Paperlib 变得臃肿。
> 
> 目前最贴近你的使用方式的操作是：
> 
> 右键一篇论文，点击 Show in Finder/Explore ，然后就会打开文件管理器了。在里面，你右键那个文件，再通过系统的右键菜单选择用任何你喜欢的软件打开就可以了。
> 
> 会考虑直接把 ‘使用 xxx 打开’ 这种功能加到 Paperlib 的右键菜单里，但是临时应该不会考虑内置 PDF 阅读器。

我想他指的应该是能够指定其他 pdf 阅读器来默认打开论文，像 zotero 一样。即保持系统的默认 PDF 打开方式不变以方便浏览其他类型的 PDF 文件，而在 paperlib 里面设置专门的 PDF 阅读器（如一些知名的具备划词取译功能的软件）来打开论文，而不是内置 PDF 阅读器。

**Comment by GeoffreyChen777** [comment]
> 



> > 
> 
> > 哦哦，目前 Paperlib 应该是不会支持浏览 PDF 的功能的。目前的定位是管理软件，PDF 阅读器有大量的优秀的阅读器，所以自己做一个这样的功能，没法说能不能做的比别人好，而且也会让 Paperlib 变得臃肿。
> > 目前最贴近你的使用方式的操作是：
> > 右键一篇论文，点击 Show in Finder/Explore ，然后就会打开文件管理器了。在里面，你右键那个文件，再通过系统的右键菜单选择用任何你喜欢的软件打开就可以了。
> > 会考虑直接把 ‘使用 xxx 打开’ 这种功能加到 Paperlib 的右键菜单里，但是临时应该不会考虑内置 PDF 阅读器。
> 
> 我想他指的应该是能够指定其他 pdf 阅读器来默认打开论文，像 zotero 一样。即保持系统的默认 PDF 打开方式不变以方便浏览其他类型的 PDF 文件，而在 paperlib 里面设置专门的 PDF 阅读器（如一些知名的具备划词取译功能的软件）来打开论文，而不是内置 PDF 阅读器。

我明白他的意思，目前版本能做到的是右键一篇论文，点击 Show in Finder/Explore ，然后就会打开文件管理器了。在里面，你右键那个文件，再通过系统的右键菜单选择用任何你喜欢的软件打开就可以了。

之后的版本会加上选择打开方式的选项。

**Comment by GeoffreyChen777** [comment]
@hairfull @layer-3 

v1.10.0 版本可以选择阅读器了，在设置里选一下就可以了。

**Comment by hairfull** [comment]
首先，感谢！其次在这两天使用的过程中，发现这个功能会把非PDF文件也用选择的pdf阅读器打开。比如添加的md文件也会被默认用pdf阅读器打开，然后因为格式不支持而打开失败。

**Comment by GeoffreyChen777** [comment]
收到，尽快修复

**Comment by GeoffreyChen777** [comment]
@hairfull 修复了，如果还有问题请联系我
