### ISSUE TITLE
Latest version seems broken on MacOS Catalina

### ISSUE THREAD

**Issue by trappmartin** [GeoffreyChen777/paperlib#155]
```
node:electron/js2c/asar_bundle:5 

Uncaught Error: dlopen(/var/folders/x5/t6vcthr52wgfk1sxzds6d3qm0349lj/T/.dev.paperlib.app.2QAVYC, 1): Symbol not found: __ZNKSt3__115basic_stringbufIcNS_11char_traitsIcEENS_9allocatorIcEEE3strEv
  Referenced from: /var/folders/x5/t6vcthr52wgfk1sxzds6d3qm0349lj/T/.dev.paperlib.app.2QAVYC (which was built for Mac OS X 12.0)
  Expected in: /usr/lib/libc++.1.dylib

    at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1812)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1199:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:5:2039)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13343)
    at Function.i._load (node:electron/js2c/renderer_init:33:356)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at bindings (/Users/trappm1/Desktop/Paperlib.app/Contents/Resources/app.asar/node_modules/bindings/bindings.js:112:48)
   ```

**Comment by GeoffreyChen777** [comment]
Hi thanks for your report.

Could you please share more information:

1. What's the previous version you used ?
2. What's is your exact macOS version?

**Comment by trappmartin** [comment]
1. I'm not entirely sure, but I think the version before `2.0.3 (2.0.3)`.
2. 10.15.7

**Comment by trappmartin** [comment]
Is there some cache that I could clean? The update might have broken it.

**Comment by GeoffreyChen777** [comment]
Let me build a new package with previous denpendency version and share it with you to see if it works. I updated some dependency in the recent releases.

**Comment by GeoffreyChen777** [comment]
Hi could you please try 2.0.0 first. There are a lot of changes in this version. It help me to locate your error.

Don't click update.

https://github.com/GeoffreyChen777/paperlib/releases/download/release-electron-2.0.0/Paperlib_2.0.0.dmg

**Comment by trappmartin** [comment]
`2.0.0` doesn't seem to work either. Same error.

**Comment by GeoffreyChen777** [comment]
Ok, thanks!

Currently, please stay at 1.10.2 I think this version should work for you.

https://github.com/GeoffreyChen777/paperlib/releases/download/release-electron-1.10.2/Paperlib_1.10.2.dmg

Give me sometime to fix this. I need to install an virtual machine of macOS 10.15.7. I will fix it ASAP.

I will notify you once I fix it.

**Comment by trappmartin** [comment]
OK, thanks a lot! Btw. I think the update broke something. Now this version (1.10.2) also doesn't run anymore. I'm pasting a screenshot of the error below, maybe that helps. 

![Screen Shot 2022-10-04 at 15 54 07](https://user-images.githubusercontent.com/7974003/193824477-19ecd14d-9c81-408d-9277-afc3122ceaac.png)

**Comment by trappmartin** [comment]
Perfect, thx!

**Comment by GeoffreyChen777** [comment]
Hi, could you please try this build:

https://objectstorage.uk-london-1.oraclecloud.com/n/lrarf8ozesjn/b/bucket-20220130-2329/o/distribution%2Ftemp%2FPaperlib_2.0.3.dmg

Just download it and replace the version in your mac.

I tried it on my virtual machine. It seems work.

If this build works, you can keep it and I believe you can receive future updates as normal.

If you still get an error, just let me know.

Best.
