### ISSUE TITLE
pdf乱码

### ISSUE THREAD

**Issue by 760985933** [GeoffreyChen777/paperlib#170]
![image](https://user-images.githubusercontent.com/23353564/197381365-bd961c6e-e9da-4dac-8157-37b98ae2e205.png)

**Comment by GeoffreyChen777** [comment]
如果可能请分享一下这个文件

**Comment by 760985933** [comment]
[6354f5b19f5e24300c2f662b_main.pdf](https://github.com/GeoffreyChen777/paperlib/files/9846029/6354f5b19f5e24300c2f662b_main.pdf)

**Comment by 760985933** [comment]
> 如果可能请分享一下这个文件
好几个文件都是这样，麻烦看看。已点start
[NUMA_6354f5369f5e24300c2f660e_main.pdf](https://github.com/GeoffreyChen777/paperlib/files/9846066/NUMA_6354f5369f5e24300c2f660e_main.pdf)

**Comment by GeoffreyChen777** [comment]
我看了一下，这不是乱码，这是单纯的中文显示不出来，只留下了英文。

如果你是一个全英文的 PDF，应该是不存在这个问题的。

如果是中文PDF，使用外部PDF浏览器打开，也是没问题的。但是内置的那个简单的浏览器，是没显示出来的。

你可以双击用外部PDF浏览器试试是不是打开没问题。

**Comment by GeoffreyChen777** [comment]
refer to #171
