### ISSUE TITLE
Title extraction and preview of papers in Chinese.

### ISSUE THREAD

**Issue by 760985933** [GeoffreyChen777/paperlib#171]
![image](https://user-images.githubusercontent.com/23353564/197382460-a762251d-ade4-4ae8-986d-45674c7be8f0.png)

当前修改，不管是title还是fulltitle都与当时拖入的pdf名称不一致且可读性差，建议保持拖入时pdf名称，不需要重命名。

**Comment by GeoffreyChen777** [comment]
这个不太可能哦，需要保持文件的识别和唯一性。如果有papaerlib的存在，从设计上是不需要去文件夹找pdf这个操作的。一切的管理和检索的入口是paperlib。

**Comment by 760985933** [comment]
> 这个不太可能哦，需要保持文件的识别和唯一性。如果有papaerlib的存在，从设计上是不需要去文件夹找pdf这个操作的。一切的管理和检索的入口是paperlib。

支持采导入时名称+唯一ID的方式也行。

**Comment by GeoffreyChen777** [comment]
重命名的规则，有自定义选项，我觉得应该能满足大部分需求了吧，请问您是想何种格式来重命名？

**Comment by 760985933** [comment]
> 重命名的规则，有自定义选项，我觉得应该能满足大部分需求了吧，请问您是想何种格式来重命名？

修改后的标题+id来命名

**Comment by GeoffreyChen777** [comment]
我的意思就是重命名成什么是有一定的自定义性的，设置界面可以自己设定，是这些规则不满足您的需求吗？另外，您是在什么情况下需要从文件夹访问pdf呢？理论上paperlib的这个文件夹应该被当做一个永远不会手动访问的文件夹才对。所有的增删改查操作都是通过paperlib界面进行。

**Comment by 760985933** [comment]
> 我的意思就是重命名成什么是有一定的自定义性的，设置界面可以自己设定，是这些规则不满足您的需求吗？另外，您是在什么情况下需要从文件夹访问pdf呢？理论上paperlib的这个文件夹应该被当做一个永远不会手动访问的文件夹才对。所有的增删改查操作都是通过paperlib界面进行。

如图，按定义规则命名，好像没有达到预期效果，很多pdf名称没有按title来。
![image](https://user-images.githubusercontent.com/23353564/197383113-71a5df7e-272f-4859-9264-935f578ff19e.png)

**Comment by GeoffreyChen777** [comment]
1）首先您看一下在您设置完规则之后再拖入的PDF们能否按照规则重命名。
2）其次我看您大部分都是中文PDF，paperlib目前从未测试过中文pdf，所以如果1）的答案是否的话，麻烦您分享一两个您重命名失败的pdf我研究一下

**Comment by 760985933** [comment]
> 
看起来是因为中文的原因，英文部分正常。我理解title可以按照两个方式实现：
1.如果是导入内容，按导入时命名。
2.如果时已存在内容，重新设置可以按照实际paperlib里面title来重命名，这样避免中文影响，直接写入title名称即可。
![image](https://user-images.githubusercontent.com/23353564/197383450-44fa4891-5b69-4062-a26c-091ec280aa47.png)

**Comment by GeoffreyChen777** [comment]
整个问题来源于无法读取中文的内容导致的。包括你的另一个issue。也是这个问题。

这需要先看看如何解决中文的问题。因为之前从未试过中文内容。

**Comment by 760985933** [comment]
> > 我的意思就是重命名成什么是有一定的自定义性的，设置界面可以自己设定，是这些规则不满足您的需求吗？另外，您是在什么情况下需要从文件夹访问pdf呢？理论上paperlib的这个文件夹应该被当做一个永远不会手动访问的文件夹才对。所有的增删改查操作都是通过paperlib界面进行。
> 
> 如图，按定义规则命名，好像没有达到预期效果，很多pdf名称没有按title来。 ![image](https://user-images.githubusercontent.com/23353564/197383113-71a5df7e-272f-4859-9264-935f578ff19e.png)

因为我们这里会存储一份PDF，我本地还有个文档文件夹也有一份，如果名称能按我自己命名的或者说跟之前导入时名称一致，我就可以只用paperlib了，后续分享给他人就不需要在命名pdf名称。

**Comment by 760985933** [comment]
> 整个问题来源于无法读取中文的内容导致的。包括你的另一个issue。也是这个问题。
> 
> 这需要先看看如何解决中文的问题。因为之前从未试过中文内容。

好的，我觉得这个软件非常帮，希望更加完善。

**Comment by GeoffreyChen777** [comment]
现在包括各种元数据搜寻器，都没有设计中文相关。如果您的文件大部分都是中文PDF，那我想现在的使用应该体验很差。几乎搜不到任何元数据

**Comment by 760985933** [comment]
> 

是的。中文内容可读性还是比较差的。

**Comment by GeoffreyChen777** [comment]
您好，中文 PDF 的显示和读取问题已经在新版本修复了。但是中文 PDF 的元数据检索目前效果可能还不好。因为我不太清楚除了知网还有哪里能做这个事，但是知网很可惜并不开放 API。

**Comment by HaoxuanGuo** [comment]
@GeoffreyChen777 Zotero的[茉莉花](https://github.com/l0o0/jasminum)插件是怎么做的，有可能模仿一下吗？

**Comment by 760985933** [comment]
您好，我已收到您发送的邮件，等待我查看内容后给您回复。

**Comment by GeoffreyChen777** [comment]
> @GeoffreyChen777 Zotero的[茉莉花](https://github.com/l0o0/jasminum)插件是怎么做的，有可能模仿一下吗？

请安装 paperlib-cn-scrape-extension
