### ISSUE TITLE
[Feature Request] Is it possible to link the file instead of copy and rename a file?

### ISSUE THREAD

**Issue by Raibows** [GeoffreyChen777/paperlib#173]
Basically, I organize papers by the directory (e.g., classification folder). And I have alreadly given these files meaningful names, like ``CVPR16-ResNet-kaimang he.pdf``. I don't want to lose them which could help me identify these papers quickly. 

So I wonder if it is possible to just link the original paper instead of moving them to the storage of Paperlib and then renaming them.
And if this feature is implemented, we could have another column ``File Name`` (similar to ``Year`` and ``Publication``) to show the original meaningful name.

From the aspect of current strategy of organizing paper files, these files are all stored in the root directory of Paperlib, lacking of subfolers to store them separately. That will be a little bit messy if we want to directly access them by the file explorer instead of with the help of Paperlib.
Taking a link to the original file may be a better way.

Actually, neither of Zotero and Mendeley could provide this feature. I hope Paperlib could take it into consideration. 

Thanks for the amazing and modern Paperlib!

**Comment by GeoffreyChen777** [comment]
The design of paperlib is the storage folder is a black box. Could you please explain why you need to access the papers from file explorer? Thanks!

**Comment by Raibows** [comment]
> The design of paperlib is the storage folder is a black box. Could you please explain why you need to access the papers from file explorer? Thanks!

Here are two main reasons:

1. I don't want to lose my legacy. So I think importing a link is better than moving and renaming a file. The file name is tailor made contaning useful information. Maybe a compromise way is to keep a record of the original file name?
2. Paperlib is good but I want to reserve high-realiability ways to organize and access my data, like directly using with the file explorer.

**Comment by GeoffreyChen777** [comment]
For these existing papers, that is ok to link them rather than moving them.

But what about newly imported papers?

how would paperlib know where to store and rename your files?

**Comment by Raibows** [comment]
> For these existing papers, that is ok to link them rather than moving them.
> 
> But what about newly imported papers?
> 
> how would paperlib know where to store and rename your files?

Newly imported papers follow the same way as the old existing papers. I download and place them in somewhere I prefer, then import them to the paperlib as a link if we have this option.
It's okay to directly import them and transfer the ownnership including file location to paperlib just like current strategy.

So, providing a link option for importing papers may help with my issue.

**Comment by GeoffreyChen777** [comment]
Ok I need to investigate if it is doable for this link option.

**Comment by Raibows** [comment]
Thanks! Really appreciate it.

**Comment by GeoffreyChen777** [comment]
May I ask which OS do you use?

I found that it is easy-to-be-implemented in macOS / Linux, but for Win:

Windows doesn't allow a non-admin user to create symlinks. If you have admin permission, it is required to turn on the developer mode of the Win system to enable symlinks creation.

**Comment by Raibows** [comment]
> May I ask which OS do you use?
> 
> I found that it is easy-to-be-implemented in macOS / Linux, but for Win:
> 
> Windows doesn't allow a non-admin user to create symlinks. If you have admin permission, it is required to turn on the developer mode of the Win system to enable symlinks creation.

I use windows. 🤣 ummmm, the link be something to find the file of course including a symbol/hard link, which also indicates a path record or a file stored the real path (just like the symbol link) are okay.

Happy to discuss about the details!

**Comment by GeoffreyChen777** [comment]
I'm releasing a version which implement this via symlink. But for windows you need to turn on the developer mode. If you have the admin permission of your PC, it is very easy to turn it on.

Does this work for you?

(Hardlink is not a good solution, because it cannot sync changes of the original file.)

**Comment by Raibows** [comment]
> I'm releasing a version which implement this via symlink. But for windows you need to turn on the developer mode. If you have the admin permission of your PC, it is very easy to turn it on.
> 
> Does this work for you?
> 
> (Hardlink is not a good solution, because it cannot sync changes of the original file.)

Yeah, thanks for your work. That will help me. How about take a path record in the database?

**Comment by GeoffreyChen777** [comment]
Ummm, currently, Paperlib stores a root dir (library folder) and relative paths of all PDFs in the database. You may be thinking that we can store the absolute path for each PDF to implement your required feature. But it is not ok because many users use Paperlib across different PC/Mac. Every device has a different file tree.

And I think it is not easy to record path in a database. the reason is that I need to modify many parts of the file backend code (file state checking such as existing, isFile, isFolder, copy/cut ops, high performance indexing for numerous paths etc.).


Could you please try to turn on the developer mode and try the new version to see if it satisfiies your requirement first? :)

**Comment by GeoffreyChen777** [comment]
V2.0.7 is released. Feel free to reopen this issue if it cannot satisfy your requirement or you find any bug of this feature.

**Comment by Raibows** [comment]
@GeoffreyChen777 It works well for me. And you don't have to turn on the windows developer mode. Just need to add the user to the ``create symbol link`` privilege list in ``Security Settings/Local Policies/User Rights Assignment/Create symbolic links``. 

Thanks!
