### ISSUE TITLE
Sort Tags in the Mainview

### ISSUE THREAD

**Issue by woodwm** [GeoffreyChen777/paperlib#175]
Hi,

I would like to suggest a feature which shows tags in a way like github issue.

paperlib supports organise papers using folders and tags where they have the same purpose and tags may be more flexible. paperlib supports assigning a colour to a tag, but this colour only shows in the tag plane, which is much less useful. Zotero adds a coloured square in the beginning of a item, which is great, but it is very easy to forget the meaning of a colour. When there are many tags and colours, it is not easy to know what tags each item has in the plane of all papers or a folder. 

I think github issue offers a very good example of showing tags for a list of items, which displays coloured tags with name after the issue name. Probably paperlib may show tags in a similar way in the third line after the source name.

**Comment by GeoffreyChen777** [comment]
Hi, are you talking about tags at here?

<img width="732" alt="image" src="https://user-images.githubusercontent.com/14183213/198876490-e732c988-0153-411d-983f-d1bf74a1f1d7.png">

I have tried some options:

1) colorize the text
2) add a small leading box just like I did in the detail panel

<img width="88" alt="image" src="https://user-images.githubusercontent.com/14183213/198876530-81e756e7-fb01-4f8a-b764-f58bea06b071.png">

But they both look a bit messy.  I don't want this colorful stuff to attract too much attention, I want to keep the hierarchy of information organized.

Do you think tags are important information for you when you look through your library? We can discuss about this.

**Comment by woodwm** [comment]
Amazing. I find it really support showing the name of tags in the mainView. Name of a tag is more important than a color. 
But probably we can think of priority of tags. Coloured tags have higher priority than others and will show in front of other tags. I use a read tag in Zotero.

**Comment by GeoffreyChen777** [comment]
About priority, in the sidebar, paperlib provides an option to sort tags at here:

<img width="750" alt="image" src="https://user-images.githubusercontent.com/14183213/198877018-f5c3d166-5f8c-437b-9a05-d08f27e16043.png">

But currently it cannot affect the tag order in the mainview.

I can investigate whether I can do sorting in the main view as well. I guess it is doable.

About read/unread, actually I've discussed this here:

[Feature request] separate reading and done read papers #114

But I have some questions about this feature. I don't know when should I mark a paper as read. If you have any idea please go to that issue and leave your comments.

**Comment by GeoffreyChen777** [comment]
Inplemented in v2.1.0
