### ISSUE TITLE
Show number of citations

### ISSUE THREAD

**Issue by woodwm** [GeoffreyChen777/paperlib#183]
One unique property of academic papers is citations. I used [Zotero Scholar Citations](https://github.com/beloglazov/zotero-scholar-citations) to show the number of citation in Zotero. I like it a lot. 

One potential issue is that google scholar does not allow frequent automatic query. Uses have to manually update the number of citations. I can accept that. It is better than noting. Probably in the future, paperlib can allow users to share the number of citations to a paperlib's database to ease the problem.

**Comment by GeoffreyChen777** [comment]
Inplemented in v2.1.0
