### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by tricktreat** [GeoffreyChen777/paperlib#188]
Very useful tool. But I got this error after installing it on either Mac or Windows system.

<img width="506" alt="image" src="https://user-images.githubusercontent.com/25740077/200174202-352b6812-561c-4ac1-bc7e-b3dbadb5d65a.png">

**Comment by GeoffreyChen777** [comment]
Hi what’s your os system?

**Comment by tricktreat** [comment]
MAC 13.0 and Windows 11

**Comment by GeoffreyChen777** [comment]
Both have this error?

**Comment by tricktreat** [comment]
Yes, same on the windows.

**Comment by tricktreat** [comment]
And I installed version 2.1.0 and 2.0.7, both with the same error.

![image](https://user-images.githubusercontent.com/25740077/200174713-ed4eae5d-162c-4cf9-8c13-8ca3b9f14e84.png)

**Comment by GeoffreyChen777** [comment]
Are you a new user of paperlib?

**Comment by tricktreat** [comment]
Yes, just heard about this tool an hour ago.

**Comment by GeoffreyChen777** [comment]
Interesting 🤔

**Comment by GeoffreyChen777** [comment]
Give me sometime to figure it out. I tried on my Mac but can’t reproduce your issue.

**Comment by tricktreat** [comment]
I just installed v2.0.6 and it‘s ok on my Windows.

**Comment by GeoffreyChen777** [comment]
emmm what about update to 2.1.0 now?

**Comment by tricktreat** [comment]
It seems that there is no direct upgrade entry in the software, so I upgrade through the installer. After the upgrade, it also works.

**Comment by GeoffreyChen777** [comment]
Seems there is an issue of configuration since 2.0.7 for new users. Apologies for that.

**Comment by GeoffreyChen777** [comment]
Have you tried 2.0.6 on your Mac? Is it ok?

**Comment by tricktreat** [comment]
Yes, it works well on mac.

**Comment by GeoffreyChen777** [comment]
OK really thank you for reporting this!

**Comment by tricktreat** [comment]
But now, after configuring cloud sync on Windows, the software won't open again. 

![image](https://user-images.githubusercontent.com/25740077/200178023-17de8061-45e9-4fee-8cc7-c630e4f25e23.png)

**Comment by GeoffreyChen777** [comment]
😂😂😂

**Comment by tricktreat** [comment]
> But now, after configuring cloud sync on Windows, the software won't open again.
> 
> ![image](https://user-images.githubusercontent.com/25740077/200178023-17de8061-45e9-4fee-8cc7-c630e4f25e23.png)

It is OK on Mac, after configuration, it can still be opened.

**Comment by GeoffreyChen777** [comment]
Do you have WeChat? Let me add you if you are ok with it? 

WeChat: geoffreychen777

**Comment by GeoffreyChen777** [comment]
Fixed.
