### ISSUE TITLE
[Feature Request] Manage proceeding/transaction information more friendly

### ISSUE THREAD

**Issue by xpsair** [GeoffreyChen777/paperlib#193]
I really appreciate your time and effort on this great tool!

How about adding a feature to make proceeding/transaction information independent from a specific paper, so that assigning a paper to a proceeding or updating the proceeding information for its papers could be more easily. 

As you know, many high-quality research papers are mostly published in some major conferences/transactions. It would be more convenient for users to manage this shared conference/transaction information friendlier. Take the following common use cases as the example: 
1. If I have completed the proceeding information for one paper and now I’m attempting to edit another paper from the same proceeding, it would be wonderful for Paperlib to assist me in completing its missing proceeding information, which is similar to auto-completion in code editors.
2. If I correct the proceeding information, proceeding location for example, all papers of this proceeding will automatically update their proceeding locations.

This feature would improve the research experience if there are hundreds of papers. Hope this feature request could be considered if possible. Many thanks!

**Comment by GeoffreyChen777** [comment]
Hi, it sounds like Paperlib cannot scrape correct metadata for many papers in your library?

if it is true, please tell me your discipline and give me some papers in your research topic. I will optimize the metadata scrapers.

Because Paperlib is designed in such a way that the user barely needs to modify any metadata manually.

**Comment by xpsair** [comment]
Hi, thanks for your prompt reply. 

I use the top-tier USENIX and IEEE/ACM conference paper`.bib` files (not PDF files) below to see whether Paperlib's built-in scrapers could effectively update their metadata.

1.  https://www.usenix.org/conference/osdi22/presentation/vant-hof
2.  https://www.usenix.org/conference/osdi21/presentation/ahmad
3.  https://dl.acm.org/doi/10.1145/3466752.3480064

This appears to have additional issues... :( 
First, The majority of USENIX Conference papers have DOIs. 
Second, the DOI entry for the IEEE/ACM paper has not been properly parsed. 
Third, neither the publically available PDF file nor the IEEE/ACM paper information could be obtained by Paperlib. 

Writing a nice scraper tool takes time and requiring frequent updates. Actually I don't use scrape as most of them just pull information from the web, and most of the information is unformatted and appears disorganized. So I just put paper entries into my ".bib" files and manually format their information for simplicity :) .

**Comment by GeoffreyChen777** [comment]
Hi, let's first discuss this:

>  neither the publically available PDF file nor the IEEE/ACM paper information could be obtained by Paperlib.

I've tried paper 1 from usenix and paper 3 from acm. Paperlib can scrape their metadata correctly.

<img width="342" alt="image" src="https://user-images.githubusercontent.com/14183213/203546417-b1113c0c-d0e5-4849-a86f-f59280325e28.png">

<img width="339" alt="image" src="https://user-images.githubusercontent.com/14183213/203546438-cebccf63-cc00-4a6b-93f7-ac6fd73b86df.png">


Could you please share me your Paperlib metadata scrapers setting? (Open the preference window and click the scraper tab)

<img width="777" alt="image" src="https://user-images.githubusercontent.com/14183213/203546642-82a25c5d-6e1b-4901-acf8-d7b00d0a70fd.png">

**Comment by xpsair** [comment]
Sure, my Paperlib metadata scrapers setting looks like this. 

<img width="785" alt="Snipaste20221123225923" src="https://user-images.githubusercontent.com/3363680/203581131-ad5a43be-c6fd-416d-be37-4af8198ea9ce.png">


So the built-in scrapers could fetch some metadata from the web, but not in my favorite style and should be customized manualy. 

<img width="269" alt="Snipaste20221123230716" src="https://user-images.githubusercontent.com/3363680/203581497-b6895ba9-3943-49e0-ac21-832a65b186a7.png">

Paperlib could help me export paper metadata to the `.bib` and finally to LaTeX produced PDF files, while these diverse proceeding information formats looks really uncomfortable to me. 
That's the main reason I create this issue to bother you 😂 
Well, perhaps I'm too peaky for this feature 😂 


> Hi, let's first discuss this:
> 
> > neither the publically available PDF file nor the IEEE/ACM paper information could be obtained by Paperlib.
> 
> I've tried paper 1 from usenix and paper 3 from acm. Paperlib can scrape their metadata correctly.
> ...

**Comment by GeoffreyChen777** [comment]
It sounds like Paperlib can scrape metadata correctly, but you wish to modify some of them.

If i'm right, then you can implement it by yourself via the custom scraper feature of paperlib. It's very easy if you know some programming. Here is a guide:

https://paperlib.app/en/doc/metadata-scraper/custom-scraper.html

If you still don't know how to implement this, just let me know, I can give you a demo code.

**Comment by xpsair** [comment]
According to Paperlib's design, perhaps customizing the scraper is a more reasonable option so far. Anyway, appreciate your time and patience :)

**Comment by GeoffreyChen777** [comment]
If you need any help to develop a custom scraper, feel free to let me know :)
