### ISSUE TITLE
批量导入论文时，出现404Error，导致总会漏掉几篇论文

### ISSUE THREAD

**Issue by Josh00-Lu** [GeoffreyChen777/paperlib#196]
能否设计一个类似Zotero那样的功能，优先把PDF导入，然后再去搜索元数据？
<img width="250" alt="image" src="https://user-images.githubusercontent.com/74221638/210162461-0ea5051b-0169-4d40-b25c-d02f32a74887.png">

**Comment by GeoffreyChen777** [comment]
理论上，这样是不会漏才对，如果搜不到任何元数据，最后会导入一个空的条目，你仔细找找是不是。

只有PDF 文件有问题，复制不成功等这种情况，才会导入不进去。

**Comment by Josh00-Lu** [comment]
> 理论上，这样是不会漏才对，如果搜不到任何元数据，最后会导入一个空的条目，你仔细找找是不是。
> 
> 只有PDF 文件有问题，复制不成功等这种情况，才会导入不进去。

非常感谢，我现在明白了！我检查了一下是有重复的论文导入了。这个软件制作非常精美，也很有设计范儿，用起来很舒服。

感觉不少科研朋友会对对文章有**互斥**归类的需求，例如我有几篇文章ResNet、VGG、MAE、Gatys Style Transfer，我想第一层面分成“已精读”、“粗读”、“未读”，另一层面分成”网络结构改进“、”CV应用“、”训练方法改进“。已有的Tag功能包括标签、分组（本质上是两种标签），可以一定程度上对文章进行归类，但是由于Tag的可重复性，容易漏掉文章，或者一个文章具有同一个层面的2个Tag（例如”已精读“和”未读“）。

我想或许可以引入”文件夹“功能来解决？

1）**文件夹**：引入“父子文件夹”，让论文分类好，一个论文在一个文件夹中，则不出现在另一个文件夹里，或许这样更有条理。
2）进一步地，2种（甚至以上）的互斥的**文件夹**逻辑。例如支持两个种类的”文件夹“逻辑，某一个文件夹逻辑里可以对文章进行分类，不同逻辑之间不相互干扰。

冒昧给你提建议，本心希望软件越来越好，谢谢！

祝新年快乐！

**Comment by GeoffreyChen777** [comment]
感谢你的支持。


你的这个需求，抱歉我没听懂，看起来有点复杂😂。。。

你有遇到实现了这个功能的软件么，我好使用参考看看是什么意思。

如果是关于已读未读的标记，可以看看这里 #114 ，对于改需求有一些逻辑没定好，还没有做。你可以提出你的见解。

**Comment by Josh00-Lu** [comment]
> 感谢你的支持。
> 
> 你的这个需求，抱歉我没听懂，看起来有点复杂😂。。。
> 
> 你有遇到实现了这个功能的软件么，我好使用参考看看是什么意思。
> 
> 如果是关于已读未读的标记，可以看看这里 #114 ，对于该需求有一些逻辑没定好，还没有做。你可以提出你的见解。

可能我没表达清楚，就是新增一个文件夹功能，里面可以对文献进行分类？类似于Zotero里面的文件夹功能。

**Comment by GeoffreyChen777** [comment]
<img width="249" alt="Screenshot 2023-01-02 at 11 10 04" src="https://user-images.githubusercontent.com/14183213/210223575-3fd45655-1d28-42c9-b1a4-bfd63eea3d8f.png">

是这个 Collection 么。感觉就是一个层级的文件夹？

如果是层级相关的东西的话，因为牵扯到对数据库结构的大更新，所以目前没有做。

我之前设计的时候是想了想觉得单层 tag folder 就能很好完成大部分工作了，所以没做层级的。

等下次大版本更新的时候考虑开发这个功能。


你说的这个 ReadPaper 是这个么？https://readpaper.com/

**Comment by Josh00-Lu** [comment]
> <img alt="Screenshot 2023-01-02 at 11 10 04" width="249" src="https://user-images.githubusercontent.com/14183213/210223575-3fd45655-1d28-42c9-b1a4-bfd63eea3d8f.png">
> 
> 是这个 Collection 么。感觉就是一个层级的文件夹？

是的！好的 非常期待

**Comment by Josh00-Lu** [comment]
> 你说的这个 ReadPaper 是这个么？https://readpaper.com/

是的。

**Comment by GeoffreyChen777** [comment]
> > 你说的这个 ReadPaper 是这个么？https://readpaper.com/
> 
> 是的。

OK 我研究下这个软件是干嘛的有啥好用的功能，如果你知道也可以在这里列出来

**Comment by Josh00-Lu** [comment]
这个软件不足的是，文件夹文类只支持一种逻辑。感觉如果支持多种分类逻辑会不会让文献管理更方便（不过不知道好不好做？）
![image](https://user-images.githubusercontent.com/74221638/210224646-f5b527ba-d860-430b-a6a7-de5ac01a0df7.png)
类似这个样子

**Comment by GeoffreyChen777** [comment]
啊我终于看懂你什么意思了。你想在不同的逻辑下，展示不同结构的分类列表层级。我简单想了想，貌似不容易做😂。因为相当于要抽象出一个新的概念“逻辑”，然后每个逻辑存储一个树状图。

我不太清楚你是在什么状况下需要用这个需求。但是我感觉这个需求似乎在层级文件夹下就可以实现。相当于你把你这里的所谓的逻辑 Tab，变为所有文件夹的最高层父文件夹。然后“文件夹-逻辑1” “文件夹-逻辑2” 下面分别开始建立自文件夹。

不知道我说的对不对。
