### ISSUE TITLE
browser extension resolve papers too slow

### ISSUE THREAD

**Issue by Doragd** [GeoffreyChen777/paperlib#199]
<img width="407" alt="image" src="https://user-images.githubusercontent.com/26213546/210704007-a5535439-20b5-49ce-96ac-c040f47d3288.png">

always stuck here...

and the desktop app cannot update the new added papers quickly

**Comment by Doragd** [comment]
> When you click the extension, you should see a downloading progress bar in the app first. Can you see that?

Thanks, I found the progress bar is running.

**Comment by GeoffreyChen777** [comment]
After clicking the extension, paperlib first downloads the PDF, then scrapes the metadata.
