### ISSUE TITLE
Can't sort the list by Tags and Folders

### ISSUE THREAD

**Issue by smallyunet** [GeoffreyChen777/paperlib#200]
https://user-images.githubusercontent.com/20765689/210955352-8bf01f27-cc51-4e3c-b266-446df73c1d72.mov

Is it a bug?

**Comment by GeoffreyChen777** [comment]
Thanks for reporting this. I will fix it ASAP.

**Comment by GeoffreyChen777** [comment]
The tags/folders prop in Paperlib is an array prop of each paper object. However, sorting by an array is not supported by the database (Realm) core.

Thus, currently, I have no choice but to disable sorting by tags/folders.

I think this is not an important feature. 

Close this issue for now.
