### ISSUE TITLE
Detail view disappeared

### ISSUE THREAD

**Issue by Tabrisrei** [GeoffreyChen777/paperlib#207]
Hi, thanks for your amazing work, paperlib is really a powerful and pretty paper organization tool.
I've organized papers by it for a long time. But recently, when I click a paper ,paperlib does not display detail view on my PC.
I can not find configuration of detail view in preference. Could you please tell me how to turn it on or if it is a bug?

**Comment by GeoffreyChen777** [comment]
I guess you minimised the width of the details panel.

Hover your cursor onto the right side of the window, and drag it to the left to see if it helps.

<img width="567" alt="image" src="https://user-images.githubusercontent.com/14183213/220889637-80ededf2-fb95-47fe-a656-1845d66fa50c.png">
