### ISSUE TITLE
Support more RSS subscription format.

### ISSUE THREAD

**Issue by GeoffreyChen777** [GeoffreyChen777/paperlib#50]

**Comment by jisuoqing** [comment]
This is great. Just curious -- when arXiv rss is added, the abstract / author metadata do not show up, and only the titles are shown. I suspect it would be very useful to include the abstract / author metadata as well?
In addition, maybe it's better to move the arXiv identification number out from the title? Now it reads like `Title blablabla (arXiv:1111.11111v1 [astro-ph.GA])`.

**Comment by GeoffreyChen777** [comment]
Could you please share your feed url?

my feed url can show the abstract and everything is fine.

**Comment by jisuoqing** [comment]
For instance, I take the official url example `http://arxiv.org/rss/math.QA`on the arXiv webpage: https://arxiv.org/help/rss

**Comment by GeoffreyChen777** [comment]
@jisuoqing Hi, I usually use the feed url like:

`http://export.arxiv.org/api/query?search_query=(ti:%22object%20detection%22+OR+abs:%22object%20detection%22)+AND+cat:%22cs.CV%22&amp;sortBy=lastUpdatedDate&amp;sortOrder=descending`

This is an advanced usage example, which can combine some query condition:

`ti:%22object%20detection%22` means title contains `object detection`, `abs:%22object%20detection%22` means abstract contains `object detection`, `cat:%22cs.CV%22` means category is `cs.CV`. The response structure of your url is different from my url, and I will try to parse yours in the next version.

So now, you can use:

`http://export.arxiv.org/api/query?search_query=cat:%22math.QA%22&amp;sortBy=lastUpdatedDate&amp;sortOrder=descending`

Now you can get the article information with abstract.

However, I still found some warning when the article is written by a single author, which should be a bug. I will fix them in the next version.

**Comment by jisuoqing** [comment]
Thanks. And it seems that the long and short RSS link versions give different number of papers. Say,
`http://arxiv.org/rss/astro-ph.GA` have 30 papers, while `http://export.arxiv.org/api/query?search_query=cat:%22astro-ph.GA%22&amp;sortBy=lastUpdatedDate&amp;sortOrder=descending` only 10.

**Comment by GeoffreyChen777** [comment]
@jisuoqing  Just use `max_results=15` to get more papers, for example `http://export.arxiv.org/api/query?search_query=cat:%22astro-ph.GA%22&amp;sortBy=lastUpdatedDate&amp;sortOrder=descending;max_results=15` , you can get 15 papers.

**Comment by jisuoqing** [comment]
Thanks for sending this link! I was looking at the RSS page, not the api page.
