### ISSUE TITLE
Met a problem when I tried to install the chrome extension.

### ISSUE THREAD

**Issue by syguan96** [GeoffreyChen777/paperlib#89]
The problem is `无法对图片解码：“128.png”`. Could you give me a hint?

**Comment by GeoffreyChen777** [comment]
This is a big in chrome extension and I’ve fixed it. The new version is under review, please wait for it:)

**Comment by syguan96** [comment]
thanks very much！

**Comment by GeoffreyChen777** [comment]
Now it's ok to install the extension.
