### ISSUE TITLE
Renaming problem; Shortcut

### ISSUE THREAD

**Issue by xdchen2** [GeoffreyChen777/paperlib#91]
Hi i encountered a problem when importing a file. The app renames with its automatic convention, which causes the file name too long. Is there a way to change the naming convention and to change the short-cuts?

**Comment by GeoffreyChen777** [comment]
Thanks for your information, I will fix it in the next version

**Comment by GeoffreyChen777** [comment]
Will provide a option for it.

**Comment by xdchen2** [comment]
Sorry, besides, I think I didn’t; get it across. When I say shortcuts I mean shortcuts for opening the file etc. Right now every time I enter a space, the app will consider it as a command to open the Review mode. It would be good to revise the default shortcuts like ’space’ for ‘review’ and ‘enter’ for ‘open the file’. Thanks!!

On Jun 24, 2022, at 14:19, GeoffreyChen777 ***@***.******@***.***>> wrote:



Will provide a option for it.

**Comment by GeoffreyChen777** [comment]
You wanna change the default shortcut, right?

**Comment by GeoffreyChen777** [comment]
Will do that in the recent version. Thanks.

**Comment by GeoffreyChen777** [comment]
solved
