### ISSUE TITLE
Directly import to a folder or tag.

### ISSUE THREAD

**Issue by shinyypig** [GeoffreyChen777/paperlib#93]
When drag a pdf file into a specific folder or tag, the added pdf is not assigned with this folder or tag. Don't know if it's a bug or the feature is not added.

**Comment by GeoffreyChen777** [comment]
Currently, tags and folders can be set only in the edit dialog.

**Comment by GeoffreyChen777** [comment]
implemented in v1.8.2

**Comment by shinyypig** [comment]
> implemented in v1.8.2

辛苦了。paperlib确实是现有的文献管理软件中最好看的，功能对我来说也够用。点赞！

**Comment by GeoffreyChen777** [comment]
> > implemented in v1.8.2
> 
> 辛苦了。paperlib确实是现有的文献管理软件中最好看的，功能对我来说也够用。点赞！

感谢您的支持，有任何其他建议和需求，都可以继续提出来，进行讨论。
