### ISSUE TITLE
[Feature Request] Support markdown notes?

### ISSUE THREAD

**Issue by Renovamen** [GeoffreyChen777/paperlib#94]
Is it possible to support markdown reading notes instead of plain-text? It would be even better if something like [KaTeX](https://github.com/KaTeX/KaTeX) could be supported.

The software is awesome, thank you for your work!

**Comment by GeoffreyChen777** [comment]
Hi, @Renovamen , currently the note only supports plaintext. If you want to write a markdown note, or any other format such as word, video, etc. , you can use a markdown editor to write a .md file and then drag drop it to the details panel. Then you will get a button like this:

<img width="318" alt="image" src="https://user-images.githubusercontent.com/14183213/175766621-0d07c959-127b-431b-b0e3-7d4ae4b28eb9.png">

**Comment by GeoffreyChen777** [comment]
implemented in v1.9.0
