### ISSUE TITLE
[Bug report] PDF opened after hitting Enter key on editing page

### ISSUE THREAD

**Issue by Renovamen** [GeoffreyChen777/paperlib#95]
The paper PDF will be opened after hitting the Enter key on editing page (for example, when I want to insert a line break in my notes), I believe it is not expected.

OS: macOS 10.15.7

![image](https://user-images.githubusercontent.com/29454156/175759741-b5aba755-63e8-4091-8753-2292201ec3d4.png)

**Comment by GeoffreyChen777** [comment]
Hi, will fix it soon. Thanks!

**Comment by GeoffreyChen777** [comment]
solved
